# Simple MSP t-SNE Configuration
# Minimal config for MSP t-SNE with sklearn pipeline

data:
  source: sklearn_digits  # sklearn_digits or file
  features: null          # Path to features file (when source=file)
  labels: null           # Path to separate labels file
  label_column: null     # Column name/index to extract from features
  format: auto           # File format: auto, csv, npy, npz, pkl, json
  allow_missing_labels: true  # Allow missing label columns

preprocessing:
  scaler: StandardScaler  # StandardScaler, MinMaxScaler, or None

algorithm:
  # MSP t-SNE parameters (same as MultiscaleParametricTSNE)
  n_components: 2
  n_iter: 1000
  batch_size: 500
  early_exaggeration_epochs: 50
  early_exaggeration_value: 4.0
  early_stopping_epochs: 1000
  early_stopping_min_improvement: 0.01
  alpha: 1.0
  lr: 0.001
  nl1: 1000
  nl2: 500
  nl3: 250
  verbose: 1

output:
  model_path: "./models/msp_tsne_pipeline.pkl"
  embeddings_path: "./models/msp_tsne_embeddings.npy"
  metrics_path: "./models/msp_tsne_metrics.json"
  overwrite_existing: true